# Quote.create!(quote: "Frankly, my dear, I don't give a damn.", author: "Gone With the Wind", category: "Movie Quotes")
# Quote.create!(quote: "I'm going to make him an offer he can't refuse.", author: "The Godfather", category: "Movie Quotes")
# Quote.create!(quote:  "Fasten your seatbelts. It's going to be a bumpy night.", author: "All About Eve", category: "Movie Quotes")
# Quote.create!(quote:  "You talking to me?", author: "Taxi Driver", category: "Movie Quotes")
# Quote.create!(quote:  "What we've got here is failure to communicate.", author: "Cool Hand Luke", category: "Movie Quotes")
# Quote.create!(quote:  "I love the smell of napalm in the morning.", author: "Apocalypse Now", category: "Movie Quotes")
# Quote.create!(quote:  "Love means never having to say you're sorry.", author: "Love Story", category: "Movie Quotes")
# Quote.create!(quote:  "The stuff that dreams are made of.", author: "The Maltese Falcon", category: "Movie Quotes")
# Quote.create!(quote:  "E.T. phone home.", author: "E.T. The Extra-Terrestrial", category: "Movie Quotes")
# Quote.create!(quote:  "They call me Mister Tibbs!", author: "In the Heat of the Night", category: "Movie Quotes")
# Quote.create!(quote:  "Made it, Ma! Top of the world!", author: "White Heat", category: "Movie Quotes")
# Quote.create!(quote:  "I'm as mad as hell, and I'm not going to take this anymore!", author: "Network", category: "Movie Quotes")
# Quote.create!(quote:  "Louis, I think this is the beginning of a beautiful friendship.", author: "Casablanca", category: "Movie Quotes")
# Quote.create!(quote:  "A census taker once tried to test me. I ate his liver with some fava beans and a nice Chianti.", author: "The Silence of the Lambs", category: "Movie Quotes")
# Quote.create!(quote:  "Bond. James Bond.", author: "Dr. No", category: "Movie Quotes")
# Quote.create!(quote:  "There's no place like home.", author: "The Wizard of Oz", category: "Movie Quotes")
# Quote.create!(quote:  "I am big! It's the pictures that got small.", author: "Sunset Blvd.", category: "Movie Quotes")
# Quote.create!(quote:  "Show me the money!", author: "Jerry Maguire", category: "Movie Quotes")
# Quote.create!(quote:  "Why don't you come up sometime and see me?", author: "She Done Him Wrong", category: "Movie Quotes")
# Quote.create!(quote:  "I'm walking here! I'm walking here!", author: "Midnight Cowboy", category: "Movie Quotes")
# Quote.create!(quote:  "Play it, Sam. Play 'As Time Goes By.'", author: "Casablanca", category: "Movie Quotes")
# Quote.create!(quote:  "You can't handle the truth!", author: "A Few Good Men", category: "Movie Quotes")
# Quote.create!(quote:  "I want to be alone.", author: "Grand Hotel", category: "Movie Quotes")
# Quote.create!(quote:  "After all, tomorrow is another day!", author: "Gone With the Wind", category: "Movie Quotes")
# Quote.create!(quote:  "Round up the usual suspects.", author: "Casablanca", category: "Movie Quotes")
# Quote.create!(quote:  "I'll have what she's having.", author: "When Harry Met Sally", category: "Movie Quotes")
# Quote.create!(quote:  "You know how to whistle, don't you, Steve? You just put your lips together and blow.", author: "To Have and Have Not", category: "Movie Quotes")
# Quote.create!(quote:  "You're gonna need a bigger boat.", author: "Jaws", category: "Movie Quotes")
# Quote.create!(quote:  "Badges? We ain't got no badges! We don't need no badges! I don't have to show you any stinking badges!", author: "The Treasure of the Sierra Madre", category: "Movie Quotes")
# Quote.create!(quote:  "I'll be back.", author: "The Terminator", category: "Movie Quotes")
# Quote.create!(quote:  "Today, I consider myself the luckiest man on the face of the earth.", author: "The Pride of the Yankees", category: "Movie Quotes")
# Quote.create!(quote:  "If you build it, he will come.", author: "Field of Dreams", category: "Movie Quotes")
# Quote.create!(quote:  "Mama always said life was like a box of chocolates. You never know what you're gonna get.", author: "Forrest Gump", category: "Movie Quotes")
# Quote.create!(quote:  "We rob banks.", author: "Bonnie and Clyde", category: "Movie Quotes")
# Quote.create!(quote:  "We'll always have Paris.", author: "Casablanca", category: "Movie Quotes")
# Quote.create!(quote:  "I see dead people.", author: "The Sixth Sense", category: "Movie Quotes")
# Quote.create!(quote:  "Stella! Hey, Stella!", author: "A Streetcar Named Desire", category: "Movie Quotes")
# Quote.create!(quote:  "Oh, Jerry, don't let's ask for the moon. We have the stars.", author: "Now, Voyager", category: "Movie Quotes")
# Quote.create!(quote:  "Shane. Shane. Come back!", author: "Shane", category: "Movie Quotes")
# Quote.create!(quote:  "Well, nobody's perfect.", author: "Some Like It Hot", category: "Movie Quotes")
# Quote.create!(quote:  "It's alive! It's alive!", author: "Frankenstein", category: "Movie Quotes")
# Quote.create!(quote:  "Houston, we have a problem.", author: "Apollo 13", category: "Movie Quotes")
# Quote.create!(quote:  "You've got to ask yourself one question: 'Do I feel lucky?' Well, do ya, punk?", author: "Dirty Harry", category: "Movie Quotes")
# Quote.create!(quote:  "You had me at ‘hello.’", author: "Jerry Maguire", category: "Movie Quotes")
# Quote.create!(quote:  "One morning I shot an elephant in my pajamas. How he got in my pajamas, I don't know.", author: "Animal Crackers", category: "Movie Quotes")
# Quote.create!(quote:  "There's no crying in baseball!", author: "A League of Their Own", category: "Movie Quotes")
# Quote.create!(quote:  "La-dee-da, la-dee-da.", author: "Annie Hall", category: "Movie Quotes")
# Quote.create!(quote:  "A boy's best friend is his mother.", author: "Psycho", category: "Movie Quotes")
# Quote.create!(quote:  "Greed, for lack of a better word, is good.", author: "Wall Street", category: "Movie Quotes")
# Quote.create!(quote:  "Keep your friends close, but your enemies closer.", author: "The Godfather II", category: "Movie Quotes")
# Quote.create!(quote:  "As God is my witness, I'll never be hungry again.", author: "Gone With the Wind", category: "Movie Quotes")
# Quote.create!(quote:  "Well, here's another nice mess you've gotten me into!", author: "Sons of the Desert", category: "Movie Quotes")
# Quote.create!(quote:  "Say hello to my little friend!", author: "Scarface", category: "Movie Quotes")
# Quote.create!(quote:  "What a dump.", author: "Beyond the Forest", category: "Movie Quotes")
# Quote.create!(quote:  "Mrs. Robinson, you're trying to seduce me. Aren't you?", author: "The Graduate", category: "Movie Quotes")
# Quote.create!(quote:  "Gentlemen, you can't fight in here! This is the War Room!", author: "Dr. Strangelove", category: "Movie Quotes")
# Quote.create!(quote:  "Elementary, my dear Watson.", author: "The Adventures of Sherlock Holmes", category: "Movie Quotes")
# Quote.create!(quote:  "Get your stinking paws off me, you damned dirty ape.", author: "Planet of the Apes", category: "Movie Quotes")
# Quote.create!(quote:  "Of all the gin joints in all the towns in all the world, she walks into mine.", author: "Casablanca", category: "Movie Quotes")
# Quote.create!(quote:  "Here's Johnny!", author: "The Shining", category: "Movie Quotes")
# Quote.create!(quote:  "They're here!", author: "Poltergeist", category: "Movie Quotes")
# Quote.create!(quote:  "Is it safe?", author: "Marathon Man", category: "Movie Quotes")
# Quote.create!(quote:  "Wait a minute, wait a minute. You ain't heard nothin' yet!", author: "The Jazz Singer", category: "Movie Quotes")
# Quote.create!(quote:  "No wire hangers, ever!", author: "Mommie Dearest", category: "Movie Quotes")
# Quote.create!(quote:  "Mother of mercy, is this the end of Rico?", author: "Little Caesar", category: "Movie Quotes")
# Quote.create!(quote:  "Forget it, Jake, it's Chinatown.", author: "Chinatown", category: "Movie Quotes")
# Quote.create!(quote:  "I have always depended on the kindness of strangers.", author: "A Streetcar Named Desire", category: "Movie Quotes")
# Quote.create!(quote:  "Hasta la vista, baby.", author: "Terminator 2: Judgment Day", category: "Movie Quotes")
# Quote.create!(quote:  "Soylent Green is people!", author: "Soylent Green", category: "Movie Quotes")
# Quote.create!(quote:  "Open the pod bay doors, HAL.", author: "2001: A Space Odyssey", category: "Movie Quotes")
# Quote.create!(quote:  "Yo, Adrian!", author: "Rocky", category: "Movie Quotes")
# Quote.create!(quote:  "Hello, gorgeous.", author: "Funny Girl", category: "Movie Quotes")
# Quote.create!(quote:  "Toga! Toga!", author: "National Lampoon's Animal House", category: "Movie Quotes")
# Quote.create!(quote:  "Listen to them. Children of the night. What music they make.", author: "Dracula", category: "Movie Quotes")
# Quote.create!(quote:  "Oh, no, it wasn't the airplanes. It was Beauty killed the Beast.", author: "King Kong", category: "Movie Quotes")
# Quote.create!(quote:  "My precious.", author: "The Lord of the Rings: Two Towers", category: "Movie Quotes")
# Quote.create!(quote:  "Attica! Attica!", author: "Dog Day Afternoon", category: "Movie Quotes")
# Quote.create!(quote:  "Sawyer, you're going out a youngster, but you've got to come back a star!", author: "42nd Street", category: "Movie Quotes")
# Quote.create!(quote:  "Listen to me, mister. You're my knight in shining armor. Don't you forget it. You're going to get back on that horse, and I'm going to be right behind you, holding on tight, and away we're gonna go, go, go!", author: "On Golden Pond", category: "Movie Quotes")
# Quote.create!(quote:  "Tell 'em to go out there with all they got and win just one for the Gipper.", author: "Knute Rockne All American", category: "Movie Quotes")
# Quote.create!(quote:  "A martini. Shaken, not stirred.", author: "Goldfinger", category: "Movie Quotes")
# Quote.create!(quote:  "Who's on first.", author: "The Naughty Nineties", category: "Movie Quotes")
# Quote.create!(quote:  "Cinderella story. Outta nowhere. A former greenskeeper, now, about to become the Masters champion. It looks like a mirac...It's in the hole! It's in the hole! It's in the hole!", author: "Caddyshack", category: "Movie Quotes")
# Quote.create!(quote:  "Life is a banquet, and most poor suckers are starving to death!", author: "Auntie Mame", category: "Movie Quotes")
# Quote.create!(quote:  "I feel the need - the need for speed!", author: "Top Gun", category: "Movie Quotes")
# Quote.create!(quote:  "Carpe diem. Seize the day, boys. Make your lives extraordinary.", author: "Dead Poets Society", category: "Movie Quotes")
# Quote.create!(quote:  "Snap out of it!", author: "Moonstruck", category: "Movie Quotes")
# Quote.create!(quote:  "My mother thanks you. My father thanks you. My sister thanks you. And I thank you.", author: "Yankee Doodle Dandy", category: "Movie Quotes")
# Quote.create!(quote:  "Nobody puts Baby in a corner.", author: "Dirty Dancing", category: "Movie Quotes")
# Quote.create!(quote:  "I'll get you, my pretty, and your little dog, too!", author: "The Wizard of Oz", category: "Movie Quotes")
# Quote.create!(quote:  "I'm king of the world!", author: "Titanic", category: "Movie Quotes")
Quote.create!(quote:  "Carolina Hurricanes", author: "NHL", category: "Professional Sport Teams")
Quote.create!(quote:  "Columbus Blue Jackets", author: "NHL", category: "Professional Sport Teams")
Quote.create!(quote:  "New Jersey Devils", author: "NHL", category: "Professional Sport Teams")
Quote.create!(quote:  "New York Islanders", author: "NHL", category: "Professional Sport Teams")
Quote.create!(quote:  "New York Rangers", author: "NHL", category: "Professional Sport Teams")
Quote.create!(quote:  "Philadelphia Flyers", author: "NHL", category: "Professional Sport Teams")
Quote.create!(quote:  "Pittsburgh Penguins", author: "NHL", category: "Professional Sport Teams")
Quote.create!(quote:  "Washington Capitals", author: "NHL", category: "Professional Sport Teams")
Quote.create!(quote:  "Boston Bruins", author: "NHL", category: "Professional Sport Teams")
Quote.create!(quote:  "Buffalo Sabres", author: "NHL", category: "Professional Sport Teams")
Quote.create!(quote:  "Detroit Red Wings", author: "NHL", category: "Professional Sport Teams")
Quote.create!(quote:  "Florida Panthers", author: "NHL", category: "Professional Sport Teams")
Quote.create!(quote:  "Montreal Canadiens", author: "NHL", category: "Professional Sport Teams")
Quote.create!(quote:  "Ottawa Senators", author: "NHL", category: "Professional Sport Teams")
Quote.create!(quote:  "Tampa Bay Lightning", author: "NHL", category: "Professional Sport Teams")
Quote.create!(quote:  "Toronto Maple Leafs", author: "NHL", category: "Professional Sport Teams")
Quote.create!(quote:  "Chicago Blackhawks", author: "NHL", category: "Professional Sport Teams")
Quote.create!(quote:  "Colorado Avalanche", author: "NHL", category: "Professional Sport Teams")
Quote.create!(quote:  "Dallas Stars", author: "NHL", category: "Professional Sport Teams")
Quote.create!(quote:  "Minnesota Wild", author: "NHL", category: "Professional Sport Teams")
Quote.create!(quote:  "Nashville Predators", author: "NHL", category: "Professional Sport Teams")
Quote.create!(quote:  "St. Louis Blues", author: "NHL", category: "Professional Sport Teams")
Quote.create!(quote:  "Winnipeg Jets", author: "NHL", category: "Professional Sport Teams")
Quote.create!(quote:  "Anaheim Ducks", author: "NHL", category: "Professional Sport Teams")
Quote.create!(quote:  "Arizona Coyotes", author: "NHL", category: "Professional Sport Teams")
Quote.create!(quote:  "Calgary Flames", author: "NHL", category: "Professional Sport Teams")
Quote.create!(quote:  "Edmonton Oilers", author: "NHL", category: "Professional Sport Teams")
Quote.create!(quote:  "Los Angeles Kings", author: "NHL", category: "Professional Sport Teams")
Quote.create!(quote:  "San Jose Sharks", author: "NHL", category: "Professional Sport Teams")
Quote.create!(quote:  "Vancouver Canucks", author: "NHL", category: "Professional Sport Teams")
Quote.create!(quote:  "Vegas Golden Knights", author: "NHL", category: "Professional Sport Teams")
Quote.create!(quote:  "Atlanta Braves", author: "MLB", category: "Professional Sport Teams")
Quote.create!(quote:  "Miami Marlins", author: "MLB", category: "Professional Sport Teams")
Quote.create!(quote:  "New York Mets", author: "MLB", category: "Professional Sport Teams")
Quote.create!(quote:  "Philadelphia Phillies", author: "MLB", category: "Professional Sport Teams")
Quote.create!(quote:  "Washington Nationals", author: "MLB", category: "Professional Sport Teams")
Quote.create!(quote:  "Chicago Cubs", author: "MLB", category: "Professional Sport Teams")
Quote.create!(quote:  "Cincinnati Reds", author: "MLB", category: "Professional Sport Teams")
Quote.create!(quote:  "Milwaukee Brewers", author: "MLB", category: "Professional Sport Teams")
Quote.create!(quote:  "Pittsburgh Pirates", author: "MLB", category: "Professional Sport Teams")
Quote.create!(quote:  "St. Louis Cardinals", author: "MLB", category: "Professional Sport Teams")
Quote.create!(quote:  "Arizona Diamondbacks", author: "MLB", category: "Professional Sport Teams")
Quote.create!(quote:  "Colorado Rockies", author: "MLB", category: "Professional Sport Teams")
Quote.create!(quote:  "Los Angeles Dodgers", author: "MLB", category: "Professional Sport Teams")
Quote.create!(quote:  "San Diego Padres", author: "MLB", category: "Professional Sport Teams")
Quote.create!(quote:  "San Francisco Giants", author: "MLB", category: "Professional Sport Teams")
Quote.create!(quote:  "Baltimore Orioles", author: "MLB", category: "Professional Sport Teams")
Quote.create!(quote:  "Boston Red Sox", author: "MLB", category: "Professional Sport Teams")
Quote.create!(quote:  "New York Yankees", author: "MLB", category: "Professional Sport Teams")
Quote.create!(quote:  "Tampa Bay Rays", author: "MLB", category: "Professional Sport Teams")
Quote.create!(quote:  "Toronto Blue Jays", author: "MLB", category: "Professional Sport Teams")
Quote.create!(quote:  "Chicago White Sox", author: "MLB", category: "Professional Sport Teams")
Quote.create!(quote:  "Cleveland Indians", author: "MLB", category: "Professional Sport Teams")
Quote.create!(quote:  "Detroit Tigers", author: "MLB", category: "Professional Sport Teams")
Quote.create!(quote:  "Kansas City Royals", author: "MLB", category: "Professional Sport Teams")
Quote.create!(quote:  "Minnesota Twins", author: "MLB", category: "Professional Sport Teams")
Quote.create!(quote:  "Houston Astros", author: "MLB", category: "Professional Sport Teams")
Quote.create!(quote:  "Los Angeles Angels", author: "MLB", category: "Professional Sport Teams")
Quote.create!(quote:  "Oakland Athletics", author: "MLB", category: "Professional Sport Teams")
Quote.create!(quote:  "Seattle Mariners", author: "MLB", category: "Professional Sport Teams")
Quote.create!(quote:  "Texas Rangers", author: "MLB", category: "Professional Sport Teams")
Quote.create!(quote:  "Buffalo Bills", author: "NFL", category: "Professional Sport Teams")
Quote.create!(quote:  "Miami Dolphins", author: "NFL", category: "Professional Sport Teams")
Quote.create!(quote:  "New England Patriots", author: "NFL", category: "Professional Sport Teams")
Quote.create!(quote:  "New York Jets", author: "NFL", category: "Professional Sport Teams")
Quote.create!(quote:  "Baltimore Ravens", author: "NFL", category: "Professional Sport Teams")
Quote.create!(quote:  "Cincinnati Bengals", author: "NFL", category: "Professional Sport Teams")
Quote.create!(quote:  "Cleveland Browns", author: "NFL", category: "Professional Sport Teams")
Quote.create!(quote:  "Pittsburgh Steelers", author: "NFL", category: "Professional Sport Teams")
Quote.create!(quote:  "Houston Texans", author: "NFL", category: "Professional Sport Teams")
Quote.create!(quote:  "Indianapolis Colts", author: "NFL", category: "Professional Sport Teams")
Quote.create!(quote:  "Jacksonville Jaguars", author: "NFL", category: "Professional Sport Teams")
Quote.create!(quote:  "Tennessee Titans", author: "NFL", category: "Professional Sport Teams")
Quote.create!(quote:  "Denver Broncos", author: "NFL", category: "Professional Sport Teams")
Quote.create!(quote:  "Kansas City Chiefs", author: "NFL", category: "Professional Sport Teams")
Quote.create!(quote:  "Oakland Raiders", author: "NFL", category: "Professional Sport Teams")
Quote.create!(quote:  "Los Angeles Chargers", author: "NFL", category: "Professional Sport Teams")
Quote.create!(quote:  "Dallas Cowboys", author: "NFL", category: "Professional Sport Teams")
Quote.create!(quote:  "New York Giants", author: "NFL", category: "Professional Sport Teams")
Quote.create!(quote:  "Philadelphia Eagles", author: "NFL", category: "Professional Sport Teams")
Quote.create!(quote:  "Washington Redskins", author: "NFL", category: "Professional Sport Teams")
Quote.create!(quote:  "Chicago Bears", author: "NFL", category: "Professional Sport Teams")
Quote.create!(quote:  "Detroit Lions", author: "NFL", category: "Professional Sport Teams")
Quote.create!(quote:  "Green Bay Packers", author: "NFL", category: "Professional Sport Teams")
Quote.create!(quote:  "Minnesota Vikings", author: "NFL", category: "Professional Sport Teams")
Quote.create!(quote:  "Atlanta Falcons", author: "NFL", category: "Professional Sport Teams")
Quote.create!(quote:  "Carolina Panthers", author: "NFL", category: "Professional Sport Teams")
Quote.create!(quote:  "New Orleans Saints", author: "NFL", category: "Professional Sport Teams")
Quote.create!(quote:  "Tampa Bay Buccaneers", author: "NFL", category: "Professional Sport Teams")
Quote.create!(quote:  "Arizona Cardinals", author: "NFL", category: "Professional Sport Teams")
Quote.create!(quote:  "Los Angeles Rams", author: "NFL", category: "Professional Sport Teams")
Quote.create!(quote:  "San Francisco 49ers", author: "NFL", category: "Professional Sport Teams")
Quote.create!(quote:  "Seattle Seahawks", author: "NFL", category: "Professional Sport Teams")
Quote.create!(quote:  "Boston Celtics", author: "NBA", category: "Professional Sport Teams")
Quote.create!(quote:  "New Jersey Nets", author: "NBA", category: "Professional Sport Teams")
Quote.create!(quote:  "New York Knicks", author: "NBA", category: "Professional Sport Teams")
Quote.create!(quote:  "Philadelphia 76ers", author: "NBA", category: "Professional Sport Teams")
Quote.create!(quote:  "Toronto Raptors", author: "NBA", category: "Professional Sport Teams")
Quote.create!(quote:  "Chicago Bulls", author: "NBA", category: "Professional Sport Teams")
Quote.create!(quote:  "Cleveland Cavaliers", author: "NBA", category: "Professional Sport Teams")
Quote.create!(quote:  "Detroit Pistons", author: "NBA", category: "Professional Sport Teams")
Quote.create!(quote:  "Indiana Pacers", author: "NBA", category: "Professional Sport Teams")
Quote.create!(quote:  "Milwaukee Bucks", author: "NBA", category: "Professional Sport Teams")
Quote.create!(quote:  "Atlanta Hawks", author: "NBA", category: "Professional Sport Teams")
Quote.create!(quote:  "Charlotte Bobcats", author: "NBA", category: "Professional Sport Teams")
Quote.create!(quote:  "Miami Heat", author: "NBA", category: "Professional Sport Teams")
Quote.create!(quote:  "Orlando Magic", author: "NBA", category: "Professional Sport Teams")
Quote.create!(quote:  "Washington Wizards", author: "NBA", category: "Professional Sport Teams")
Quote.create!(quote:  "Denver Nuggets", author: "NBA", category: "Professional Sport Teams")
Quote.create!(quote:  "Minnesota Timberwolves", author: "NBA", category: "Professional Sport Teams")
Quote.create!(quote:  "Oklahoma City Thunder", author: "NBA", category: "Professional Sport Teams")
Quote.create!(quote:  "Portland Trail Blazers", author: "NBA", category: "Professional Sport Teams")
Quote.create!(quote:  "Utah Jazz", author: "NBA", category: "Professional Sport Teams")
Quote.create!(quote:  "Golden State Warriors", author: "NBA", category: "Professional Sport Teams")
Quote.create!(quote:  "Los Angeles Clippers", author: "NBA", category: "Professional Sport Teams")
Quote.create!(quote:  "Los Angeles Lakers", author: "NBA", category: "Professional Sport Teams")
Quote.create!(quote:  "Phoenix Suns", author: "NBA", category: "Professional Sport Teams")
Quote.create!(quote:  "Dallas Mavericks", author: "NBA", category: "Professional Sport Teams")
Quote.create!(quote:  "Houston Rockets", author: "NBA", category: "Professional Sport Teams")
Quote.create!(quote:  "Memphis Grizzlies", author: "NBA", category: "Professional Sport Teams")
Quote.create!(quote:  "New Orleans Hornets", author: "NBA", category: "Professional Sport Teams")
Quote.create!(quote:  "San Antonio Spurs", author: "NBA", category: "Professional Sport Teams")
Quote.create!(quote:  "I will survive! Oh as long as I know how to love I know I will stay alive!", author: "Gloria Gaynor ", category: "Song Lyrics")
Quote.create!(quote:  "I won't be afraid just as long as you stand, stand by me.", author: "Ben E. King", category: "Song Lyrics")
Quote.create!(quote:  "I'm a survivor, I'm not gonna give up, I'm not gonna stop, I'm gonna work harder.", author: "Destiny's Child", category: "Song Lyrics")
Quote.create!(quote:  "I hear babies cry, I watch them grow, They'll learn much more, Than I'll ever know. And I think to myself, What a wonderful World", author: "Louis Armstrong", category: "Song Lyrics")
Quote.create!(quote:  "Sing with me, sing for the year, sing for the laughter, and sing it for the tear.", author: " Aerosmith", category: "Song Lyrics")
Quote.create!(quote:  "In every life we have some trouble. But when you worry, you make it double.", author: "Bobby McFerrin", category: "Song Lyrics")
Quote.create!(quote:  "All you need is love, love. Love is all your need.", author: "The Beatles", category: "Song Lyrics")
Quote.create!(quote:  "You only get one shot, do not miss your chance to blow. This opportunity comes once in a lifetime", author: "Eminem", category: "Song Lyrics")
Quote.create!(quote:  "Get up, stand up! Don’t give up the fight!", author: "Bob Marley ", category: "Song Lyrics")
Quote.create!(quote:  "You may say I'm a dreamer. But I'm not the only one.", author: "John Lennon", category: "Song Lyrics")`

# Player.create!(name: "Tom")
# Player.create!(name: "Jason")


