Quote.create!(quote: "Frankly, my dear, I don't give a damn.", author: "Gone With the Wind", category: "Movie Quotes")
Quote.create!(quote: "I'm going to make him an offer he can't refuse.", author: "The Godfather", category: "Movie Quotes")
Quote.create!(quote:  "You talking to me?", author: "Taxi Driver", category: "Movie Quotes")
Quote.create!(quote:  "What we've got here is failure to communicate.", author: "Cool Hand Luke", category: "Movie Quotes")
Quote.create!(quote:  "I love the smell of napalm in the morning.", author: "Apocalypse Now", category: "Movie Quotes")
Quote.create!(quote:  "E.T. phone home.", author: "E.T. The Extra-Terrestrial", category: "Movie Quotes")
Quote.create!(quote:  "Bond. James Bond.", author: "James Bond: Dr. No", category: "Movie Quotes")
Quote.create!(quote:  "There's no place like home.", author: "The Wizard of Oz", category: "Movie Quotes")
Quote.create!(quote:  "Show me the money!", author: "Jerry Maguire", category: "Movie Quotes")
Quote.create!(quote:  "You can't handle the truth!", author: "A Few Good Men", category: "Movie Quotes")
Quote.create!(quote:  "I'll have what she's having.", author: "When Harry Met Sally", category: "Movie Quotes")
Quote.create!(quote:  "You're gonna need a bigger boat.", author: "Jaws", category: "Movie Quotes")
Quote.create!(quote:  "I'll be back.", author: "The Terminator", category: "Movie Quotes")
Quote.create!(quote:  "If you build it, he will come.", author: "Field of Dreams", category: "Movie Quotes")
Quote.create!(quote:  "Mama always said life was like a box of chocolates.", author: "Forrest Gump", category: "Movie Quotes")
Quote.create!(quote:  "I see dead people.", author: "The Sixth Sense", category: "Movie Quotes")
Quote.create!(quote:  "Stella! Hey, Stella!", author: "A Streetcar Named Desire", category: "Movie Quotes")
Quote.create!(quote:  "It's alive! It's alive!", author: "Frankenstein", category: "Movie Quotes")
Quote.create!(quote:  "Houston, we have a problem.", author: "Apollo 13", category: "Movie Quotes")
Quote.create!(quote:  "You had me at ‘hello.’", author: "Jerry Maguire", category: "Movie Quotes")
Quote.create!(quote:  "There's no crying in baseball!", author: "A League of Their Own", category: "Movie Quotes")
Quote.create!(quote:  "Greed, for lack of a better word, is good.", author: "Wall Street", category: "Movie Quotes")
Quote.create!(quote:  "Keep your friends close, but your enemies closer.", author: "The Godfather II", category: "Movie Quotes")
Quote.create!(quote:  "Say hello to my little friend!", author: "Scarface", category: "Movie Quotes")
Quote.create!(quote:  "What a dump.", author: "Beyond the Forest", category: "Movie Quotes")
Quote.create!(quote:  "Mrs. Robinson, you're trying to seduce me. Aren't you?", author: "The Graduate", category: "Movie Quotes")
Quote.create!(quote:  "Elementary, my dear Watson.", author: "The Adventures of Sherlock Holmes", category: "Movie Quotes")
Quote.create!(quote:  "you damned dirty ape.", author: "Planet of the Apes", category: "Movie Quotes")
Quote.create!(quote:  "Here's Johnny!", author: "The Shining", category: "Movie Quotes")
Quote.create!(quote:  "They're here!", author: "Poltergeist", category: "Movie Quotes")
Quote.create!(quote:  "Is it safe?", author: "Marathon Man", category: "Movie Quotes")
Quote.create!(quote:  "Hasta la vista, baby.", author: "Terminator 2: Judgment Day", category: "Movie Quotes")
Quote.create!(quote:  "Soylent Green is people!", author: "Soylent Green", category: "Movie Quotes")
Quote.create!(quote:  "Yo, Adrian!", author: "Rocky", category: "Movie Quotes")
Quote.create!(quote:  "Toga! Toga!", author: "National Lampoon's Animal House", category: "Movie Quotes")
Quote.create!(quote:  "My precious.", author: "The Lord of the Rings: Two Towers", category: "Movie Quotes")
Quote.create!(quote:  "A martini. Shaken, not stirred.", author: "James Bond: Goldfinger", category: "Movie Quotes")
Quote.create!(quote:  "Who's on first.", author: "The Naughty Nineties", category: "Movie Quotes")
Quote.create!(quote:  "I feel the need - the need for speed!", author: "Top Gun", category: "Movie Quotes")
Quote.create!(quote:  "Carpe diem. Seize the day, boys.", author: "Dead Poets Society", category: "Movie Quotes")
Quote.create!(quote:  "I'll get you, my pretty", author: "The Wizard of Oz", category: "Movie Quotes")
Quote.create!(quote:  "I'm king of the world!", author: "Titanic", category: "Movie Quotes")
Quote.create!(quote: "Carolina Hurricanes", author: "NHL", category: "Professional Sports Teams")
Quote.create!(quote:  "Columbus Blue Jackets", author: "NHL", category: "Professional Sport Teams")
Quote.create!(quote:  "New Jersey Devils", author: "NHL", category: "Professional Sport Teams")
Quote.create!(quote:  "New York Islanders", author: "NHL", category: "Professional Sport Teams")
Quote.create!(quote:  "New York Rangers", author: "NHL", category: "Professional Sport Teams")
Quote.create!(quote:  "Philadelphia Flyers", author: "NHL", category: "Professional Sport Teams")
Quote.create!(quote:  "Pittsburgh Penguins", author: "NHL", category: "Professional Sport Teams")
Quote.create!(quote:  "Washington Capitals", author: "NHL", category: "Professional Sport Teams")
Quote.create!(quote:  "Boston Bruins", author: "NHL", category: "Professional Sport Teams")
Quote.create!(quote:  "Buffalo Sabres", author: "NHL", category: "Professional Sport Teams")
Quote.create!(quote:  "Detroit Red Wings", author: "NHL", category: "Professional Sport Teams")
Quote.create!(quote:  "Florida Panthers", author: "NHL", category: "Professional Sport Teams")
Quote.create!(quote:  "Montreal Canadiens", author: "NHL", category: "Professional Sport Teams")
Quote.create!(quote:  "Ottawa Senators", author: "NHL", category: "Professional Sport Teams")
Quote.create!(quote:  "Tampa Bay Lightning", author: "NHL", category: "Professional Sport Teams")
Quote.create!(quote:  "Toronto Maple Leafs", author: "NHL", category: "Professional Sport Teams")
Quote.create!(quote:  "Chicago Blackhawks", author: "NHL", category: "Professional Sport Teams")
Quote.create!(quote:  "Colorado Avalanche", author: "NHL", category: "Professional Sport Teams")
Quote.create!(quote:  "Dallas Stars", author: "NHL", category: "Professional Sport Teams")
Quote.create!(quote:  "Minnesota Wild", author: "NHL", category: "Professional Sport Teams")
Quote.create!(quote:  "Nashville Predators", author: "NHL", category: "Professional Sport Teams")
Quote.create!(quote:  "St. Louis Blues", author: "NHL", category: "Professional Sport Teams")
Quote.create!(quote:  "Winnipeg Jets", author: "NHL", category: "Professional Sport Teams")
Quote.create!(quote:  "Anaheim Ducks", author: "NHL", category: "Professional Sport Teams")
Quote.create!(quote:  "Arizona Coyotes", author: "NHL", category: "Professional Sport Teams")
Quote.create!(quote:  "Calgary Flames", author: "NHL", category: "Professional Sport Teams")
Quote.create!(quote:  "Edmonton Oilers", author: "NHL", category: "Professional Sport Teams")
Quote.create!(quote:  "Los Angeles Kings", author: "NHL", category: "Professional Sport Teams")
Quote.create!(quote:  "San Jose Sharks", author: "NHL", category: "Professional Sport Teams")
Quote.create!(quote:  "Vancouver Canucks", author: "NHL", category: "Professional Sport Teams")
Quote.create!(quote:  "Vegas Golden Knights", author: "NHL", category: "Professional Sport Teams")
Quote.create!(quote:  "Atlanta Braves", author: "MLB", category: "Professional Sport Teams")
Quote.create!(quote:  "Miami Marlins", author: "MLB", category: "Professional Sport Teams")
Quote.create!(quote:  "New York Mets", author: "MLB", category: "Professional Sport Teams")
Quote.create!(quote:  "Philadelphia Phillies", author: "MLB", category: "Professional Sport Teams")
Quote.create!(quote:  "Washington Nationals", author: "MLB", category: "Professional Sport Teams")
Quote.create!(quote:  "Chicago Cubs", author: "MLB", category: "Professional Sport Teams")
Quote.create!(quote:  "Cincinnati Reds", author: "MLB", category: "Professional Sport Teams")
Quote.create!(quote:  "Milwaukee Brewers", author: "MLB", category: "Professional Sport Teams")
Quote.create!(quote:  "Pittsburgh Pirates", author: "MLB", category: "Professional Sport Teams")
Quote.create!(quote:  "St. Louis Cardinals", author: "MLB", category: "Professional Sport Teams")
Quote.create!(quote:  "Arizona Diamondbacks", author: "MLB", category: "Professional Sport Teams")
Quote.create!(quote:  "Colorado Rockies", author: "MLB", category: "Professional Sport Teams")
Quote.create!(quote:  "Los Angeles Dodgers", author: "MLB", category: "Professional Sport Teams")
Quote.create!(quote:  "San Diego Padres", author: "MLB", category: "Professional Sport Teams")
Quote.create!(quote:  "San Francisco Giants", author: "MLB", category: "Professional Sport Teams")
Quote.create!(quote:  "Baltimore Orioles", author: "MLB", category: "Professional Sport Teams")
Quote.create!(quote:  "Boston Red Sox", author: "MLB", category: "Professional Sport Teams")
Quote.create!(quote:  "New York Yankees", author: "MLB", category: "Professional Sport Teams")
Quote.create!(quote:  "Tampa Bay Rays", author: "MLB", category: "Professional Sport Teams")
Quote.create!(quote:  "Toronto Blue Jays", author: "MLB", category: "Professional Sport Teams")
Quote.create!(quote:  "Chicago White Sox", author: "MLB", category: "Professional Sport Teams")
Quote.create!(quote:  "Cleveland Indians", author: "MLB", category: "Professional Sport Teams")
Quote.create!(quote:  "Detroit Tigers", author: "MLB", category: "Professional Sport Teams")
Quote.create!(quote:  "Kansas City Royals", author: "MLB", category: "Professional Sport Teams")
Quote.create!(quote:  "Minnesota Twins", author: "MLB", category: "Professional Sport Teams")
Quote.create!(quote:  "Houston Astros", author: "MLB", category: "Professional Sport Teams")
Quote.create!(quote:  "Los Angeles Angels", author: "MLB", category: "Professional Sport Teams")
Quote.create!(quote:  "Oakland Athletics", author: "MLB", category: "Professional Sport Teams")
Quote.create!(quote:  "Seattle Mariners", author: "MLB", category: "Professional Sport Teams")
Quote.create!(quote:  "Texas Rangers", author: "MLB", category: "Professional Sport Teams")
Quote.create!(quote:  "Buffalo Bills", author: "NFL", category: "Professional Sport Teams")
Quote.create!(quote:  "Miami Dolphins", author: "NFL", category: "Professional Sport Teams")
Quote.create!(quote:  "New England Patriots", author: "NFL", category: "Professional Sport Teams")
Quote.create!(quote:  "New York Jets", author: "NFL", category: "Professional Sport Teams")
Quote.create!(quote:  "Baltimore Ravens", author: "NFL", category: "Professional Sport Teams")
Quote.create!(quote:  "Cincinnati Bengals", author: "NFL", category: "Professional Sport Teams")
Quote.create!(quote:  "Cleveland Browns", author: "NFL", category: "Professional Sport Teams")
Quote.create!(quote:  "Pittsburgh Steelers", author: "NFL", category: "Professional Sport Teams")
Quote.create!(quote:  "Houston Texans", author: "NFL", category: "Professional Sport Teams")
Quote.create!(quote:  "Indianapolis Colts", author: "NFL", category: "Professional Sport Teams")
Quote.create!(quote:  "Jacksonville Jaguars", author: "NFL", category: "Professional Sport Teams")
Quote.create!(quote:  "Tennessee Titans", author: "NFL", category: "Professional Sport Teams")
Quote.create!(quote:  "Denver Broncos", author: "NFL", category: "Professional Sport Teams")
Quote.create!(quote:  "Kansas City Chiefs", author: "NFL", category: "Professional Sport Teams")
Quote.create!(quote:  "Oakland Raiders", author: "NFL", category: "Professional Sport Teams")
Quote.create!(quote:  "Los Angeles Chargers", author: "NFL", category: "Professional Sport Teams")
Quote.create!(quote:  "Dallas Cowboys", author: "NFL", category: "Professional Sport Teams")
Quote.create!(quote:  "New York Giants", author: "NFL", category: "Professional Sport Teams")
Quote.create!(quote:  "Philadelphia Eagles", author: "NFL", category: "Professional Sport Teams")
Quote.create!(quote:  "Washington Redskins", author: "NFL", category: "Professional Sport Teams")
Quote.create!(quote:  "Chicago Bears", author: "NFL", category: "Professional Sport Teams")
Quote.create!(quote:  "Detroit Lions", author: "NFL", category: "Professional Sport Teams")
Quote.create!(quote:  "Green Bay Packers", author: "NFL", category: "Professional Sport Teams")
Quote.create!(quote:  "Minnesota Vikings", author: "NFL", category: "Professional Sport Teams")
Quote.create!(quote:  "Atlanta Falcons", author: "NFL", category: "Professional Sport Teams")
Quote.create!(quote:  "Carolina Panthers", author: "NFL", category: "Professional Sport Teams")
Quote.create!(quote:  "New Orleans Saints", author: "NFL", category: "Professional Sport Teams")
Quote.create!(quote:  "Tampa Bay Buccaneers", author: "NFL", category: "Professional Sport Teams")
Quote.create!(quote:  "Arizona Cardinals", author: "NFL", category: "Professional Sport Teams")
Quote.create!(quote:  "Los Angeles Rams", author: "NFL", category: "Professional Sport Teams")
Quote.create!(quote:  "San Francisco 49ers", author: "NFL", category: "Professional Sport Teams")
Quote.create!(quote:  "Seattle Seahawks", author: "NFL", category: "Professional Sport Teams")
Quote.create!(quote:  "Boston Celtics", author: "NBA", category: "Professional Sport Teams")
Quote.create!(quote:  "New Jersey Nets", author: "NBA", category: "Professional Sport Teams")
Quote.create!(quote:  "New York Knicks", author: "NBA", category: "Professional Sport Teams")
Quote.create!(quote:  "Philadelphia 76ers", author: "NBA", category: "Professional Sport Teams")
Quote.create!(quote:  "Toronto Raptors", author: "NBA", category: "Professional Sport Teams")
Quote.create!(quote:  "Chicago Bulls", author: "NBA", category: "Professional Sport Teams")
Quote.create!(quote:  "Cleveland Cavaliers", author: "NBA", category: "Professional Sport Teams")
Quote.create!(quote:  "Detroit Pistons", author: "NBA", category: "Professional Sport Teams")
Quote.create!(quote:  "Indiana Pacers", author: "NBA", category: "Professional Sport Teams")
Quote.create!(quote:  "Milwaukee Bucks", author: "NBA", category: "Professional Sport Teams")
Quote.create!(quote:  "Atlanta Hawks", author: "NBA", category: "Professional Sport Teams")
Quote.create!(quote:  "Charlotte Bobcats", author: "NBA", category: "Professional Sport Teams")
Quote.create!(quote:  "Miami Heat", author: "NBA", category: "Professional Sport Teams")
Quote.create!(quote:  "Orlando Magic", author: "NBA", category: "Professional Sport Teams")
Quote.create!(quote:  "Washington Wizards", author: "NBA", category: "Professional Sport Teams")
Quote.create!(quote:  "Denver Nuggets", author: "NBA", category: "Professional Sport Teams")
Quote.create!(quote:  "Minnesota Timberwolves", author: "NBA", category: "Professional Sport Teams")
Quote.create!(quote:  "Oklahoma City Thunder", author: "NBA", category: "Professional Sport Teams")
Quote.create!(quote:  "Portland Trail Blazers", author: "NBA", category: "Professional Sport Teams")
Quote.create!(quote:  "Utah Jazz", author: "NBA", category: "Professional Sport Teams")
Quote.create!(quote:  "Golden State Warriors", author: "NBA", category: "Professional Sport Teams")
Quote.create!(quote:  "Los Angeles Clippers", author: "NBA", category: "Professional Sport Teams")
Quote.create!(quote:  "Los Angeles Lakers", author: "NBA", category: "Professional Sport Teams")
Quote.create!(quote:  "Phoenix Suns", author: "NBA", category: "Professional Sport Teams")
Quote.create!(quote:  "Dallas Mavericks", author: "NBA", category: "Professional Sport Teams")
Quote.create!(quote:  "Houston Rockets", author: "NBA", category: "Professional Sport Teams")
Quote.create!(quote:  "Memphis Grizzlies", author: "NBA", category: "Professional Sport Teams")
Quote.create!(quote:  "New Orleans Hornets", author: "NBA", category: "Professional Sport Teams")
Quote.create!(quote:  "San Antonio Spurs", author: "NBA", category: "Professional Sport Teams")
Quote.create!(quote:  "I will survive!", author: "Gloria Gaynor", category: "Song Lyrics")
Quote.create!(quote:  "just as long as you stand, stand by me.", author: "Ben E. King", category: "Song Lyrics")
Quote.create!(quote:  "I'm a survivor, I'm not gonna give up.", author: "Destiny's Child", category: "Song Lyrics")
Quote.create!(quote:  "And I think to myself, What a wonderful World", author: "Louis Armstrong", category: "Song Lyrics")
Quote.create!(quote:  "Sing with me, sing for the year.", author: "Aerosmith", category: "Song Lyrics")
Quote.create!(quote:  "Dont worry, be happy.", author: "Bobby McFerrin", category: "Song Lyrics")
Quote.create!(quote:  "All you need is love. Love is all your need.", author: "The Beatles", category: "Song Lyrics")
Quote.create!(quote:  "Get up, stand up! Don’t give up the fight!", author: "Bob Marley", category: "Song Lyrics")
Quote.create!(quote:  "You may say I'm a dreamer. But I'm not the only one.", author: "John Lennon", category: "Song Lyrics")
Quote.create!(quote:  "It’s better to burn out than to fade away", author: "Neil Young", category: "Song Lyrics")
Quote.create!(quote:  "You can't always get what you wan", author: "The Rolling Stones", category: "Song Lyrics")
Quote.create!(quote:  "You gotta fight for your right to party", author: "The Beastie Boys", category: "Song Lyrics")
Quote.create!(quote:  "Slowly walking down the hall, faster than a cannonball.", author: "Oasis", category: "Song Lyrics")
Quote.create!(quote:  "Love is a battlefield.", author: "Pat Benatar", category: "Song Lyrics")
Quote.create!(quote:  "I went down down down and the flames went higher.", author: "Johnny Cash", category: "Song Lyrics")
Quote.create!(quote:  "I did it my way.", author: "Frank Sinatra", category: "Song Lyrics")
Quote.create!(quote:  "If I can make it there, I'll make it anywhere.", author: "Frank Sinatra", category: "Song Lyrics")
Quote.create!(quote:  "Hey now, you're an all star.", author: "Smash Mouth", category: "Song Lyrics")
Quote.create!(quote:  "Don't stop believin.", author: "Journey", category: "Song Lyrics")
Quote.create!(quote:  "Oh baby baby, how was I supposed to know.", author: "Britney Spears", category: "Song Lyrics")
Quote.create!(quote:  "All the small things. Work sucks. I know.", author: "Blink 182", category: "Song Lyrics")
Quote.create!(quote:  "Alabama", author: "Capital = Montgomery", category: "US States")
Quote.create!(quote:  "Alaska", author: "Capital = Juneau", category: "US States")
Quote.create!(quote:  "Arizona", author: "Capital = Phoenix", category: "US States")
Quote.create!(quote:  "Arkansas", author: "Capital = Little Rock", category: "US States")
Quote.create!(quote:  "California", author: "Capital = Sacramento", category: "US States")
Quote.create!(quote:  "Colorado", author: "Capital = Denver", category: "US States")
Quote.create!(quote:  "Connecticut", author: "Capital = Hartford", category: "US States")
Quote.create!(quote:  "Delaware", author: "Capital = Dover", category: "US States")
Quote.create!(quote:  "Florida", author: "Capital = Tallahassee", category: "US States")
Quote.create!(quote:  "Georgia", author: "Capital = Atlanta", category: "US States")
Quote.create!(quote:  "Hawaii", author: "Capital = Honolulu", category: "US States")
Quote.create!(quote:  "Idaho", author: "Capital = Boise", category: "US States")
Quote.create!(quote:  "Illinois", author: "Capital = Springfield", category: "US States")
Quote.create!(quote:  "Indiana", author: "Capital = Indianapolis", category: "US States")
Quote.create!(quote:  "Iowa", author: "Capital = Des Moines", category: "US States")
Quote.create!(quote:  "Kansas", author: "Capital = Topeka", category: "US States")
Quote.create!(quote:  "Kentucky", author: "Capital = Frankfort", category: "US States")
Quote.create!(quote:  "Louisiana", author: "Capital = Baton Rouge", category: "US States")
Quote.create!(quote:  "Maine", author: "Capital = Augusta", category: "US States")
Quote.create!(quote:  "Maryland", author: "Capital = Annapolis", category: "US States")
Quote.create!(quote:  "Massachusetts", author: "Capital = Boston", category: "US States")
Quote.create!(quote:  "Michigan", author: "Capital = Lansing", category: "US States")
Quote.create!(quote:  "Minnesota", author: "Capital = Saint Paul", category: "US States")
Quote.create!(quote:  "Mississippi", author: "Capital = Jackson", category: "US States")
Quote.create!(quote:  "Missouri", author: "Capital = Jefferson City", category: "US States")
Quote.create!(quote:  "Montana", author: "Capital = Helena", category: "US States")
Quote.create!(quote:  "Nebraska", author: "Capital = Lincoln", category: "US States")
Quote.create!(quote:  "Nevada", author: "Capital = Carson City", category: "US States")
Quote.create!(quote:  "New Hampshire", author: "Capital = Concord", category: "US States")
Quote.create!(quote:  "New Jersey", author: "Capital = Trenton", category: "US States")
Quote.create!(quote:  "New Mexico", author: "Capital = Santa Fe", category: "US States")
Quote.create!(quote:  "New York", author: "Capital = Albany", category: "US States")
Quote.create!(quote:  "North Carolina", author: "Capital = Raleigh", category: "US States")
Quote.create!(quote:  "North Dakota", author: "Capital = Bismarck", category: "US States")
Quote.create!(quote:  "Ohio", author: "Capital = Columbus", category: "US States")
Quote.create!(quote:  "Oklahoma", author: "Capital = Oklahoma City", category: "US States")
Quote.create!(quote:  "Oregon", author: "Capital = Salem", category: "US States")
Quote.create!(quote:  "Pennsylvania", author: "Capital = Harrisburg", category: "US States")
Quote.create!(quote:  "Rhode Island", author: "Capital = Providence", category: "US States")
Quote.create!(quote:  "South Carolina", author: "Capital = Columbia", category: "US States")
Quote.create!(quote:  "South Dakota", author: "Capital = Pierre", category: "US States")
Quote.create!(quote:  "Tennessee", author: "Capital = Nashville", category: "US States")
Quote.create!(quote:  "Texas", author: "Capital = Austin", category: "US States")
Quote.create!(quote:  "Utah", author: "Capital = Salt Lake City", category: "US States")
Quote.create!(quote:  "Vermont", author: "Capital = Montpelier", category: "US States")
Quote.create!(quote:  "Virginia", author: "Capital = Richmond", category: "US States")
Quote.create!(quote:  "Washington", author: "Capital = Olympia", category: "US States")
Quote.create!(quote:  "West Virginia", author: "Capital = Charleston", category: "US States")
Quote.create!(quote:  "Wisconsin", author: "Capital = Madison", category: "US States")
Quote.create!(quote:  "Wyoming", author: "Capital = Cheyenne", category: "US States")


# Player.create!(name: "Tom")
# Player.create!(name: "Jason")


